### ISSUE TITLE
canInstallLabs not working

### ISSUE THREAD

**Issue by joshualyon** [iamcanadian2222/ST-Kodi#3]
Broken for some users with virtual hubs

**Comment by iamcanadian2222** [comment]
Fixed with commit e724fa4

Filter out VIRTUAL hubs with:
`def realHubs = location.hubs*.findAll{ it.type == "PHYSICAL" }`

**Comment by joshualyon** [comment]
Fixed with commit e724fa4

Filter out VIRTUAL hubs with:
`def realHubs = location.hubs*.findAll{ it.type == "PHYSICAL" }`
