### ISSUE TITLE
Add ShowNotification

### ISSUE THREAD

**Issue by joshualyon** [iamcanadian2222/ST-Kodi#5]
http://kodi.wiki/view/JSON-RPC_API/v6#GUI.ShowNotification

`showNotification(title, message)`

```
{"jsonrpc": "2.0", "method": "GUI.ShowNotification", "params": {"title": "USERTITLE", "message": "USERMESSAGE"}, "id": 1}
```

**Comment by iamcanadian2222** [comment]
Added in 41de067

`sendNotification(title, message, [image])`

Example:
`sendNotification("Front Door", "Someone is knocking!")`

**Comment by joshualyon** [comment]
Added in 41de067

`sendNotification(title, message, [image])`

Example:
`sendNotification("Front Door", "Someone is knocking!")`
